-- ============================================================
-- Supabase (Postgres) schema for ai-video-cms
-- Derived from src/db/schema.ts + migrate.ts + API route usage.
-- Idempotent: safe to re-run.
-- Booleans use Postgres boolean (PostgREST coerces 1/0 and true/false).
-- JSON-ish columns use jsonb (data-source handles both string & object).
-- ============================================================

-- 1. videos
CREATE TABLE IF NOT EXISTS videos (
  id              text PRIMARY KEY,
  title           text NOT NULL,
  description     text DEFAULT '',
  file_path       text,
  thumbnail_path  text,
  duration        integer DEFAULT 0,
  file_size       bigint DEFAULT 0,
  status          text DEFAULT 'draft',          -- @deprecated
  publish_status  text DEFAULT 'draft',
  processing_step text DEFAULT 'none',
  source_type     text DEFAULT 'local',
  youtube_video_id text,
  youtube_url     text,
  youtube_metadata jsonb,
  youtube_channel text,
  youtube_duration integer,
  category_code   text,
  ai_prompt       text,
  program_id      integer,
  published_at    timestamptz,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- 2. programs
CREATE TABLE IF NOT EXISTS programs (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  description   text DEFAULT '',
  thumbnail_path text,
  logo_path     text,
  is_active     boolean DEFAULT true,
  created_at    timestamptz DEFAULT now()
);

-- 3. transcriptions
CREATE TABLE IF NOT EXISTS transcriptions (
  id            text PRIMARY KEY,
  video_id      text NOT NULL,
  full_text     text NOT NULL,
  segments      jsonb,
  source        text DEFAULT 'whisper',
  language      text DEFAULT 'ja',
  model         text DEFAULT 'whisper-1',
  status        text DEFAULT 'pending',
  error_message text,
  processing_ms integer,
  created_at    timestamptz DEFAULT now()
);

-- 4. ai_contents
CREATE TABLE IF NOT EXISTS ai_contents (
  id            text PRIMARY KEY,
  video_id      text NOT NULL,
  summary       text,
  chapters      jsonb,
  article       text,
  tags          jsonb,
  related_ids   text,
  related_category_codes jsonb,
  version       integer DEFAULT 1,
  model         text DEFAULT 'claude-sonnet-4-20250514',
  status        text DEFAULT 'pending',
  error_message text,
  processing_ms integer,
  is_edited     boolean DEFAULT false,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

-- 5. thumbnails
CREATE TABLE IF NOT EXISTS thumbnails (
  id            text PRIMARY KEY,
  video_id      text NOT NULL,
  file_path     text,
  source        text NOT NULL DEFAULT 'manual',
  prompt        text,
  style_preset  text,
  style_preset_id text,
  is_primary    boolean DEFAULT false,
  status        text DEFAULT 'done',
  error_message text,
  width         integer,
  height        integer,
  file_size     bigint,
  model         text,
  created_at    timestamptz DEFAULT now()
);

-- 6. thumbnail_style_presets
CREATE TABLE IF NOT EXISTS thumbnail_style_presets (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  prompt_template text NOT NULL,
  style_params    jsonb,
  is_default      boolean DEFAULT false,
  created_at      timestamptz DEFAULT now()
);

-- 7. ai_generation_logs
CREATE TABLE IF NOT EXISTS ai_generation_logs (
  id            text PRIMARY KEY,
  video_id      text NOT NULL,
  step          text NOT NULL,
  status        text DEFAULT 'pending',
  model         text,
  prompt        text,
  result_preview text,
  error_message text,
  processing_ms integer,
  created_at    timestamptz DEFAULT now()
);

-- 8. job_queue
CREATE TABLE IF NOT EXISTS job_queue (
  id            text PRIMARY KEY,
  video_id      text NOT NULL,
  job_type      text NOT NULL,
  status        text DEFAULT 'pending',
  priority      integer DEFAULT 0,
  attempts      integer DEFAULT 0,
  max_attempts  integer DEFAULT 3,
  error_message text,
  started_at    timestamptz,
  completed_at  timestamptz,
  created_at    timestamptz DEFAULT now()
);

-- 9. metrics
CREATE TABLE IF NOT EXISTS metrics (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id      text NOT NULL UNIQUE,
  view_count    integer DEFAULT 0,
  rating        real DEFAULT 0,
  rating_count  integer DEFAULT 0,
  comment_count integer DEFAULT 0
);

-- 10. categories
CREATE TABLE IF NOT EXISTS categories (
  code        text PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer DEFAULT 0
);

-- 11. ai_style_presets
CREATE TABLE IF NOT EXISTS ai_style_presets (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  description     text DEFAULT '',
  prompt_template text NOT NULL,
  is_default      boolean DEFAULT false,
  sort_order      integer DEFAULT 0,
  created_at      timestamptz DEFAULT now()
);

-- 12. system_config
CREATE TABLE IF NOT EXISTS system_config (
  key         text PRIMARY KEY,
  value       text,
  updated_at  timestamptz DEFAULT now()
);

-- 13. user_favorites (RLS — accessed with user JWT via anon key)
CREATE TABLE IF NOT EXISTS user_favorites (
  id          text PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  video_id    text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, video_id)
);

-- 14. user_watch_history (RLS — accessed with user JWT via anon key)
CREATE TABLE IF NOT EXISTS user_watch_history (
  id              text PRIMARY KEY,
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  video_id        text NOT NULL,
  watched_seconds integer NOT NULL DEFAULT 0,
  total_seconds   integer NOT NULL DEFAULT 0,
  watched_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, video_id)
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_videos_publish_status ON videos(publish_status, published_at);
CREATE INDEX IF NOT EXISTS idx_videos_program_id ON videos(program_id);
CREATE INDEX IF NOT EXISTS idx_videos_category_code ON videos(category_code);
CREATE INDEX IF NOT EXISTS idx_transcriptions_video_id ON transcriptions(video_id);
CREATE INDEX IF NOT EXISTS idx_ai_contents_video_id ON ai_contents(video_id);
CREATE INDEX IF NOT EXISTS idx_thumbnails_video_id ON thumbnails(video_id);
CREATE INDEX IF NOT EXISTS idx_metrics_video_id ON metrics(video_id);
CREATE INDEX IF NOT EXISTS idx_ai_generation_logs_video_id ON ai_generation_logs(video_id);
CREATE INDEX IF NOT EXISTS idx_job_queue_status ON job_queue(status, priority);
CREATE INDEX IF NOT EXISTS idx_watch_history_user ON user_watch_history(user_id, watched_at DESC);
CREATE INDEX IF NOT EXISTS idx_favorites_user ON user_favorites(user_id, created_at DESC);

-- ============================================================
-- Row Level Security for per-user tables
-- ============================================================
ALTER TABLE user_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_watch_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "fav_select_own" ON user_favorites;
DROP POLICY IF EXISTS "fav_insert_own" ON user_favorites;
DROP POLICY IF EXISTS "fav_update_own" ON user_favorites;
DROP POLICY IF EXISTS "fav_delete_own" ON user_favorites;
CREATE POLICY "fav_select_own" ON user_favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "fav_insert_own" ON user_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "fav_update_own" ON user_favorites FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "fav_delete_own" ON user_favorites FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "wh_select_own" ON user_watch_history;
DROP POLICY IF EXISTS "wh_insert_own" ON user_watch_history;
DROP POLICY IF EXISTS "wh_update_own" ON user_watch_history;
CREATE POLICY "wh_select_own" ON user_watch_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "wh_insert_own" ON user_watch_history FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "wh_update_own" ON user_watch_history FOR UPDATE USING (auth.uid() = user_id);

-- ============================================================
-- 解説者（MC/出演者） / プレイリスト / 検索タグ
-- 配線: src/lib/data-source.ts (getMCMembers / getMCDetail / getPlaylists / getSearchTags)
-- 投入: npx tsx --env-file=.env.local src/db/migrate-supabase-extras.ts
-- ============================================================
CREATE TABLE IF NOT EXISTS mc_members (
  id             SERIAL PRIMARY KEY,
  name           TEXT NOT NULL,
  role           TEXT DEFAULT '',
  bio            TEXT DEFAULT '',
  thumbnail_path TEXT,
  sort_order     INTEGER DEFAULT 0,
  is_active      BOOLEAN DEFAULT true,
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS video_casts (
  video_id TEXT NOT NULL,
  mc_id    INTEGER NOT NULL REFERENCES mc_members(id) ON DELETE CASCADE,
  PRIMARY KEY (video_id, mc_id)
);
CREATE INDEX IF NOT EXISTS idx_video_casts_mc ON video_casts(mc_id);

CREATE TABLE IF NOT EXISTS playlists (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT DEFAULT '',
  owner_label TEXT DEFAULT 'AI MEDIA運営',
  kind        TEXT DEFAULT 'curated',
  sort_order  INTEGER DEFAULT 0,
  is_public   BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS playlist_items (
  playlist_id TEXT NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
  video_id    TEXT NOT NULL,
  position    INTEGER DEFAULT 0,
  PRIMARY KEY (playlist_id, video_id)
);
CREATE INDEX IF NOT EXISTS idx_playlist_items_pl ON playlist_items(playlist_id);

CREATE TABLE IF NOT EXISTS search_tags (
  id         SERIAL PRIMARY KEY,
  label      TEXT NOT NULL UNIQUE,
  sort_order INTEGER DEFAULT 0,
  is_active  BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);
